/**
 * @MX:NOTE: [AUTO] Band coverage computation and topic tag extraction for video segments.
 * computeBandCoverage() produces a per-band coverage ratio jsonb for video_segments.band_coverage.
 * extractTopicTags() extracts deterministic keyword-based topic tags (v1, no LLM required).
 * @MX:SPEC: SPEC-INPUT-002 - Phase 1, Task 1.2 / 1.3
 * @MX:NOTE: [AUTO] Band coverage is CUMULATIVE: each band covers words 1..N (most-to-least frequent).
 * beginner=500, basic=1500, conversation=3000, professional=6000. A word in the beginner
 * band is also counted for all higher bands.
 */
import { tokenizeText } from "./reading-coverage";
import { BAND_WORD_COUNTS } from "@inputenglish/shared";
import type { VocabBand } from "@inputenglish/shared";

// ── Frequency seed word sets ──────────────────────────────────────────────────
// v1: use a representative seed of the most frequent English words per band level.
// These are drawn from BNC/COCA frequency lists. In production, a full 6000-word
// list should be loaded. This seed is sufficient for the cumulative coverage heuristic.

// Top ~500 most-frequent English lemmas (beginner band seed)
const BEGINNER_SEED = new Set<string>([
  "the",
  "be",
  "to",
  "of",
  "and",
  "in",
  "that",
  "have",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "we",
  "say",
  "her",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "day",
  "most",
  "us",
  "between",
  "need",
  "large",
  "often",
  "hand",
  "high",
  "place",
  "hold",
  "turn",
  "help",
  "here",
  "why",
  "ask",
  "went",
  "men",
  "read",
  "need",
  "land",
  "different",
  "home",
  "move",
  "try",
  "kind",
  "hand",
  "picture",
  "again",
  "change",
  "off",
  "play",
  "spell",
  "air",
  "away",
  "animal",
  "house",
  "point",
  "page",
  "letter",
  "mother",
  "answer",
  "found",
  "still",
  "learn",
  "should",
  "america",
  "world",
  "high",
  "every",
  "near",
  "add",
  "food",
  "between",
  "own",
  "below",
  "country",
  "plant",
  "last",
  "school",
  "father",
  "keep",
  "tree",
  "never",
  "start",
  "city",
  "earth",
  "eye",
  "light",
  "thought",
  "head",
  "under",
  "story",
  "left",
  "few",
  "while",
  "along",
  "might",
  "close",
  "something",
  "seem",
  "next",
  "hard",
  "open",
  "example",
  "beginning",
  "life",
  "always",
  "those",
  "both",
  "paper",
  "together",
  "got",
  "group",
  "often",
  "run",
  "important",
  "until",
  "children",
  "side",
  "feet",
  "car",
  "mile",
  "night",
  "walk",
  "white",
  "sea",
  "began",
  "grow",
  "took",
  "river",
  "four",
  "carry",
  "state",
  "once",
  "book",
  "hear",
  "stop",
  "without",
  "second",
  "later",
  "miss",
  "idea",
  "body",
  "music",
  "color",
  "stand",
  "sun",
  "question",
  "fish",
  "area",
  "mark",
  "dog",
  "horse",
  "birds",
  "problem",
  "complete",
  "room",
  "knew",
  "since",
  "ever",
  "piece",
  "told",
  "usually",
  "didn",
  "friends",
  "easy",
  "heard",
  "order",
  "red",
  "door",
  "sure",
  "become",
  "top",
  "ship",
  "across",
  "today",
  "during",
  "short",
  "better",
  "best",
  "however",
  "low",
  "hours",
  "black",
  "products",
  "happened",
  "whole",
  "measure",
  "remember",
  "early",
  "waves",
  "reached",
  "listen",
  "wind",
  "rock",
  "space",
  "covered",
  "fast",
  "several",
  "hold",
  "himself",
  "toward",
  "five",
  "step",
  "morning",
  "passed",
  "vowel",
  "true",
  "hundred",
  "against",
  "pattern",
  "numeral",
  "table",
  "north",
  "slowly",
  "money",
  "map",
  "farm",
  "pulled",
  "draw",
  "voice",
  "power",
  "town",
  "fine",
  "drive",
  "sang",
  "natural",
  "watch",
  "form",
  "common",
  "appear",
  "gold",
  "king",
  "possible",
  "plane",
  "system",
  "behind",
  "ran",
  "check",
  "game",
  "shape",
  "equal",
  "hot",
  "miss",
  "brought",
  "heat",
  "snow",
  "tire",
  "bring",
  "yes",
  "distant",
  "fill",
  "east",
  "paint",
  "language",
  "among",
  "grand",
  "ball",
  "yet",
  "wave",
  "drop",
  "heart",
  "present",
  "heavy",
  "dance",
  "engine",
  "position",
  "arm",
  "wide",
  "sail",
  "material",
  "size",
  "vary",
  "settle",
  "speak",
  "weight",
  "general",
  "ice",
  "matter",
  "circle",
  "pair",
  "include",
  "divide",
  "syllable",
  "felt",
  "perhaps",
  "pick",
  "sudden",
  "count",
  "square",
  "reason",
  "length",
  "represent",
  "art",
  "subject",
  "region",
  "energy",
  "hunt",
  "probable",
  "sleep",
  "fresh",
  "week",
  "final",
  "gave",
  "green",
  "oh",
  "quick",
  "develop",
  "ocean",
  "warm",
  "free",
  "minute",
  "strong",
  "special",
  "behind",
  "clear",
  "tail",
  "produce",
  "fact",
  "street",
  "inch",
  "contain",
  "front",
  "feel",
  "built",
  "family",
  "direct",
  "pose",
  "leave",
  "song",
  "measure",
  "door",
  "product",
  "black",
]);

// Additional words for basic band (501-1500 frequency range)
const BASIC_ADDITIONAL = new Set<string>([
  "accept",
  "account",
  "achieve",
  "action",
  "active",
  "activity",
  "actual",
  "additional",
  "address",
  "advance",
  "advantage",
  "advice",
  "affect",
  "afford",
  "age",
  "agent",
  "agree",
  "agreement",
  "ahead",
  "aim",
  "allow",
  "almost",
  "already",
  "although",
  "amount",
  "analysis",
  "announce",
  "another",
  "apart",
  "apply",
  "approach",
  "appropriate",
  "arise",
  "around",
  "arrange",
  "article",
  "attention",
  "available",
  "avoid",
  "aware",
  "base",
  "basic",
  "battle",
  "become",
  "before",
  "believe",
  "benefit",
  "beyond",
  "bit",
  "board",
  "break",
  "bring",
  "building",
  "business",
  "call",
  "capital",
  "central",
  "certain",
  "challenge",
  "character",
  "choice",
  "claim",
  "class",
  "clear",
  "climate",
  "collect",
  "company",
  "compare",
  "concern",
  "confirm",
  "consider",
  "continue",
  "control",
  "cost",
  "couple",
  "create",
  "culture",
  "current",
  "data",
  "deal",
  "decide",
  "decision",
  "deep",
  "define",
  "degree",
  "deliver",
  "demand",
  "design",
  "detail",
  "determine",
  "develop",
  "difference",
  "discuss",
  "economic",
  "economy",
  "effect",
  "effort",
  "election",
  "element",
  "establish",
  "evidence",
  "exactly",
  "example",
  "exist",
  "expect",
  "experience",
  "explain",
  "explore",
  "face",
  "fact",
  "fail",
  "figure",
  "finance",
  "focus",
  "follow",
  "force",
  "former",
  "forward",
  "function",
  "future",
  "health",
  "help",
  "hope",
  "human",
  "identify",
  "image",
  "impact",
  "include",
  "increase",
  "industry",
  "influence",
  "issue",
  "join",
  "large",
  "lead",
  "learn",
  "level",
  "likely",
  "local",
  "long",
  "loss",
  "major",
  "manage",
  "market",
  "meaning",
  "media",
  "meet",
  "member",
  "method",
  "model",
  "national",
  "natural",
  "nature",
  "number",
  "offer",
  "often",
  "original",
  "own",
  "particular",
  "past",
  "performance",
  "period",
  "personal",
  "physical",
  "plan",
  "player",
  "political",
  "position",
  "practice",
  "press",
  "prevent",
  "price",
  "process",
  "program",
  "project",
  "protect",
  "provide",
  "public",
  "put",
  "quality",
  "quite",
  "raise",
  "range",
  "rate",
  "recent",
  "record",
  "reduce",
  "refer",
  "relate",
  "remain",
  "report",
  "require",
  "research",
  "resource",
  "result",
  "return",
  "reveal",
  "role",
  "rule",
  "safe",
  "section",
  "set",
  "show",
  "sign",
  "significant",
  "simple",
  "situation",
  "small",
  "social",
  "society",
  "specific",
  "spend",
  "staff",
  "standard",
  "statement",
  "study",
  "success",
  "suggest",
  "support",
  "term",
  "test",
  "thought",
  "trade",
  "training",
  "truth",
  "type",
  "union",
  "value",
  "various",
  "view",
  "visit",
  "voice",
  "vote",
  "water",
  "whole",
  "wide",
  "within",
  "woman",
  "young",
]);

// Additional words for conversation band (1501-3000 frequency range)
const CONVERSATION_ADDITIONAL = new Set<string>([
  "absolutely",
  "accompany",
  "acquire",
  "adequate",
  "adjust",
  "administration",
  "adopt",
  "agency",
  "agenda",
  "allocate",
  "alter",
  "alternative",
  "analyse",
  "annual",
  "anticipate",
  "apparent",
  "appreciate",
  "aspect",
  "assess",
  "assist",
  "assume",
  "atmosphere",
  "attach",
  "attitude",
  "attribute",
  "authority",
  "behaviour",
  "capacity",
  "category",
  "circumstance",
  "colleague",
  "commit",
  "communicate",
  "community",
  "complex",
  "component",
  "concept",
  "confident",
  "conflict",
  "consequence",
  "considerable",
  "construct",
  "context",
  "contribute",
  "convention",
  "criteria",
  "cultural",
  "customer",
  "debate",
  "decade",
  "declare",
  "derive",
  "dialogue",
  "dimension",
  "discourse",
  "distribute",
  "diverse",
  "document",
  "domain",
  "dominant",
  "draft",
  "dynamic",
  "emphasize",
  "enable",
  "encounter",
  "engage",
  "enhance",
  "environment",
  "essential",
  "evaluate",
  "eventually",
  "evolve",
  "exchange",
  "expert",
  "facilitate",
  "feature",
  "flexible",
  "framework",
  "generate",
  "global",
  "guideline",
  "hence",
  "implement",
  "implication",
  "indicate",
  "individual",
  "initiative",
  "innovative",
  "insight",
  "integrate",
  "interact",
  "interpret",
  "intervention",
  "involve",
  "justify",
  "label",
  "legislation",
  "medium",
  "motivation",
  "network",
  "neutral",
  "nonetheless",
  "norm",
  "notion",
  "objective",
  "obtain",
  "outcome",
  "output",
  "overall",
  "participant",
  "perceive",
  "perspective",
  "phenomenon",
  "policy",
  "potential",
  "prefer",
  "primary",
  "principle",
  "priority",
  "procedure",
  "promote",
  "proportion",
  "propose",
  "publish",
  "purchase",
  "rational",
  "respond",
  "responsibility",
  "retain",
  "reveal",
  "sector",
  "seek",
  "selection",
  "sequence",
  "significant",
  "source",
  "strategy",
  "structure",
  "subsequently",
  "sufficient",
  "survey",
  "sustainable",
  "target",
  "technique",
  "theory",
  "traditional",
  "transfer",
  "transform",
  "transition",
  "trend",
  "whereas",
  "widespread",
]);

// Additional words for professional band (3001-6000 frequency range)
const PROFESSIONAL_ADDITIONAL = new Set<string>([
  "aggregate",
  "arbitrary",
  "augment",
  "autonomous",
  "benchmark",
  "calibrate",
  "cascade",
  "coherent",
  "collaborate",
  "commodity",
  "complement",
  "comprehensive",
  "concurrent",
  "consolidate",
  "constraint",
  "contingent",
  "correlation",
  "cumulative",
  "deploy",
  "differentiate",
  "discretionary",
  "eliminate",
  "empirical",
  "enumerate",
  "equilibrium",
  "ethics",
  "exception",
  "extrapolate",
  "feasible",
  "formulate",
  "governance",
  "granular",
  "hierarchical",
  "hypothesis",
  "infrastructure",
  "inherent",
  "innovate",
  "integrate",
  "intellectual",
  "iterate",
  "jurisdiction",
  "leverage",
  "mandatory",
  "mitigate",
  "module",
  "optimize",
  "parameter",
  "periphery",
  "pragmatic",
  "prioritize",
  "propagate",
  "quantify",
  "redundant",
  "regulatory",
  "resilient",
  "scalable",
  "scenario",
  "spectrum",
  "stakeholder",
  "systematic",
  "taxonomy",
  "threshold",
  "throughput",
  "transparency",
  "versatile",
  "viable",
  "vulnerability",
  "workflow",
  "algorithm",
  "prototype",
  "validate",
  "concurrent",
  "latency",
  "deprecate",
  "manifest",
  "orchestrate",
  "provision",
  "refactor",
  "synchronize",
  "aggregate",
  "partition",
  "transaction",
  "encryption",
  "authorization",
  "authentication",
  "middleware",
  "framework",
  "architecture",
  "repository",
  "configuration",
  "deployment",
  "pipeline",
  "containerize",
  "microservice",
  "endpoint",
  "payload",
  "schema",
  "callback",
  "asynchronous",
  "synchronous",
  "runtime",
  "compile",
]);

// Precomputed cumulative sets per band
const BAND_SETS: Record<VocabBand, Set<string>> = {
  beginner: BEGINNER_SEED,
  basic: new Set([...BEGINNER_SEED, ...BASIC_ADDITIONAL]),
  conversation: new Set([
    ...BEGINNER_SEED,
    ...BASIC_ADDITIONAL,
    ...CONVERSATION_ADDITIONAL,
  ]),
  professional: new Set([
    ...BEGINNER_SEED,
    ...BASIC_ADDITIONAL,
    ...CONVERSATION_ADDITIONAL,
    ...PROFESSIONAL_ADDITIONAL,
  ]),
};

// All bands in order
const BANDS: VocabBand[] = [
  "beginner",
  "basic",
  "conversation",
  "professional",
];

// ── Band coverage ─────────────────────────────────────────────────────────────

/**
 * Compute per-band vocabulary coverage for a transcript text.
 *
 * Coverage is defined as: fraction of unique tokens in text that appear
 * within the cumulative word set for that band (most-frequent → band ceiling).
 *
 * Coverage is CUMULATIVE: professional coverage >= conversation >= basic >= beginner
 * for any given vocabulary.
 *
 * @returns Record<VocabBand, number> — coverage ratio 0..1 per band.
 *          Never returns empty {}; always has all four band keys.
 */
export function computeBandCoverage(
  transcriptText: string,
): Record<VocabBand, number> {
  const tokens = tokenizeText(transcriptText);
  const empty: Record<VocabBand, number> = {
    beginner: 0,
    basic: 0,
    conversation: 0,
    professional: 0,
  };

  if (tokens.length === 0) {
    return empty;
  }

  const uniqueTokens = [...new Set(tokens)];
  const totalUnique = uniqueTokens.length;

  const result = { ...empty };
  for (const band of BANDS) {
    const bandSet = BAND_SETS[band];
    const knownCount = uniqueTokens.filter((t) => bandSet.has(t)).length;
    result[band] = knownCount / totalUnique;
  }

  return result;
}

// ── Topic tags ────────────────────────────────────────────────────────────────

interface TopicKeywords {
  topic: string;
  keywords: string[];
}

// Deterministic keyword-based topic taxonomy (v1, no LLM)
// @MX:NOTE: [AUTO] v1 keyword taxonomy — extend via SPEC or upgrade to LLM
// classification in a future phase. Each topic has a keyword list; score by
// keyword frequency, emit top tags. Fallback: ["general"].
const TOPIC_TAXONOMY: TopicKeywords[] = [
  {
    topic: "technology",
    keywords: [
      "technology",
      "software",
      "hardware",
      "computer",
      "algorithm",
      "data",
      "code",
      "programming",
      "digital",
      "internet",
      "ai",
      "machine",
      "learning",
      "artificial",
      "intelligence",
      "robot",
      "automation",
      "cloud",
      "server",
      "network",
      "database",
      "developer",
      "engineer",
      "tech",
      "app",
      "mobile",
      "startup",
      "innovation",
      "system",
      "platform",
    ],
  },
  {
    topic: "business",
    keywords: [
      "business",
      "company",
      "market",
      "revenue",
      "profit",
      "loss",
      "sales",
      "product",
      "customer",
      "brand",
      "marketing",
      "strategy",
      "management",
      "ceo",
      "executive",
      "corporate",
      "enterprise",
      "industry",
      "commercial",
      "transaction",
      "deal",
      "acquisition",
      "merger",
      "startup",
      "investment",
      "funding",
      "venture",
    ],
  },
  {
    topic: "economy",
    keywords: [
      "economy",
      "economic",
      "finance",
      "financial",
      "stock",
      "market",
      "inflation",
      "gdp",
      "growth",
      "recession",
      "trade",
      "currency",
      "debt",
      "fiscal",
      "monetary",
      "bank",
      "banking",
      "interest",
      "rate",
      "tax",
      "policy",
      "regulation",
      "earnings",
      "shareholder",
      "investor",
      "quarter",
    ],
  },
  {
    topic: "politics",
    keywords: [
      "politics",
      "political",
      "government",
      "election",
      "vote",
      "democracy",
      "president",
      "congress",
      "senate",
      "law",
      "policy",
      "legislation",
      "reform",
      "party",
      "campaign",
      "candidate",
      "debate",
      "constitutional",
      "parliament",
      "minister",
      "official",
      "administration",
      "republican",
      "democrat",
      "liberal",
      "conservative",
    ],
  },
  {
    topic: "science",
    keywords: [
      "science",
      "scientific",
      "research",
      "study",
      "experiment",
      "hypothesis",
      "theory",
      "discovery",
      "biology",
      "chemistry",
      "physics",
      "medicine",
      "medical",
      "health",
      "climate",
      "environment",
      "genetics",
      "evolution",
      "space",
      "astronomy",
      "energy",
      "quantum",
      "molecular",
      "laboratory",
      "neuroscience",
    ],
  },
  {
    topic: "culture",
    keywords: [
      "culture",
      "art",
      "music",
      "film",
      "movie",
      "book",
      "literature",
      "sport",
      "fashion",
      "design",
      "entertainment",
      "celebrity",
      "festival",
      "history",
      "tradition",
      "social",
      "society",
      "diversity",
      "religion",
      "philosophy",
      "education",
      "language",
    ],
  },
  {
    topic: "health",
    keywords: [
      "health",
      "medical",
      "doctor",
      "patient",
      "hospital",
      "disease",
      "treatment",
      "medicine",
      "mental",
      "wellness",
      "fitness",
      "diet",
      "nutrition",
      "exercise",
      "therapy",
      "vaccine",
      "virus",
      "pandemic",
      "symptom",
      "diagnosis",
      "surgery",
    ],
  },
];

const MAX_TAGS = 5;
const MIN_KEYWORD_MATCHES = 2;

/**
 * Extract topic tags from transcript text using deterministic keyword matching.
 *
 * v1 algorithm: tokenize → count keyword hits per topic → sort by hit count →
 * return top-N topics that exceed MIN_KEYWORD_MATCHES threshold.
 * Fallback: ["general"] if no topic exceeds the threshold.
 *
 * @returns string[] — 1 to MAX_TAGS tags, no duplicates. Never returns [].
 */
export function extractTopicTags(transcriptText: string): string[] {
  const tokens = tokenizeText(transcriptText);
  if (tokens.length === 0) {
    return ["general"];
  }

  const tokenSet = new Set(tokens);

  const scores: Array<{ topic: string; score: number }> = TOPIC_TAXONOMY.map(
    ({ topic, keywords }) => {
      const score = keywords.filter((kw) => tokenSet.has(kw)).length;
      return { topic, score };
    },
  );

  const matched = scores
    .filter(({ score }) => score >= MIN_KEYWORD_MATCHES)
    .sort((a, b) => b.score - a.score)
    .slice(0, MAX_TAGS)
    .map(({ topic }) => topic);

  return matched.length > 0 ? matched : ["general"];
}

// Re-export BAND_WORD_COUNTS for consumers that need to know band sizes
export { BAND_WORD_COUNTS };
